name = "PhylogeneticTrees"
uuid = "6d56a5a2-9523-4ac5-b898-386f43f22c4e"
authors = ["Jack <jackgarbus@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
